version: '3.8'

services:
  blue:
    build:
      context: .
      dockerfile: Dockerfile
    image: nimikgnoej/tig-web:blue # 블루 환경용 이미지 태그
    ports:
      - "8081:8080" # 블루 환경 포트
    env_file:
      - .env
    environment:
      - SERVER_PORT=8080 # 내부적으로 Spring Boot는 8080으로 실행
    container_name: app-blue
    networks:
      - app-network

  green:
    build:
      context: .
      dockerfile: Dockerfile
    image: nimikgnoej/tig-web:green # 그린 환경용 이미지 태그
    ports:
      - "8082:8080" # 그린 환경 포트
    env_file:
      - .env
    environment:
      - SERVER_PORT=8080 # 내부적으로 Spring Boot는 8080으로 실행
    container_name: app-green
    networks:
      - app-network

  nginx:
    image: nimikgnoej/tig-nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile # nginx에 대한 Dockerfile
    ports:
      - "80:80" # 외부로 노출되는 포트
    env_file:
      - .env
    environment:
      - environment=${environment}
    volumes:
      - /home/ubuntu/nginx.template.conf:/etc/nginx/nginx.template.conf
    command: >
      sh -c "envsubst '$environment' < /etc/nginx/nginx.template.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    depends_on:
      - blue
      - green
    container_name: nginx
    networks:
      - app-network

networks:
  app-network:
    driver: bridge