version: '3.8'

services:
  blue:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: nimikgnoej/tig-web:blue # 블루 환경용 이미지 태그
    ports:
      - "8081:8081" # 블루 환경 포트
    env_file:
      - .env
    environment:
      - SERVER_PORT=8081
    container_name: app-blue
    networks:
      - app-network

  green:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: nimikgnoej/tig-web:green # 그린 환경용 이미지 태그
    ports:
      - "8082:8082" # 그린 환경 포트
    env_file:
      - .env
    environment:
      - SERVER_PORT=8082
    container_name: app-green
    networks:
      - app-network

  nginx:
    platform: linux/amd64
    image: nimikgnoej/tig-nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile # nginx에 대한 Dockerfile
    ports:
      - "80:80" # 외부로 노출되는 포트
      - "8085:8085"
    env_file:
      - .env
    environment:
      - environment=${environment}
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - blue
      - green
    container_name: nginx
    networks:
      - app-network

  prometheus:
    platform: linux/amd64
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/data/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - app-network
    depends_on:
      - blue
      - green

  grafana:
    platform: linux/amd64
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - prometheus


networks:
  app-network:
    driver: bridge