spring:
  data:
    redis:
      port: 6379
      host: ${EC2_PUBLIC_IP}
      password: ${REDIS_PASSWORD}
  profiles:
    active: deploy
  config:
    import: optional:file:.env[.properties]
  sql:
    init:
      mode: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,application/json

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    tagsSorter: alpha
    operations-sorter: alpha
    display-request-duration: true

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  secret: ${JWT_SECRET}
  token-validity-in-seconds: 86400 # ttl (초)


discord:
  name-join: discord-feign-join
  name-application: discord-feign-application
  name-cancel: discord-feign-cancel
webhooks:
  webhook-1: ${DISCORD_WEBHOOK_RESERVATION_APPLICATION}
  webhook-2: ${DISCORD_WEBHOOK_RESERVATION_CANCEL}
  webhook-3: ${DISCORD_WEBHOOK_JOIN}
kakao:
  client_id: ${KAKAO_CLIENT_ID}
  client_secret: ${KAKAO_SECRET_ID}
portone:
  api_key: ${PORTONE_API_KEY}
  api_secret: ${PORTONE_API_SECRET}
  v2_secret: ${PORTONE_V2_SECRET}