http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # 개발/테스트 환경 (블루) 백엔드
    upstream blue_backend {
        server app_blue:8080;
        keepalive 32;
    }

    # 사용자(운영) 환경 (그린) 백엔드
    upstream green_backend {
        server app_green:8080;
        keepalive 32;
    }

    # 사용자(운영) 환경 - 그린
    server {
        listen 80;
        server_name api.tigleisure.com;

        location / {
            proxy_pass http://green_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Health Check
        location /tig/health {
            proxy_pass http://green_backend/tig/health;
            proxy_set_header Host $host;
        }
    }

    # 개발/테스트 환경 - 블루
    server {
        listen 80;
        server_name dev.tigleisure.com;

        location / {
            proxy_pass http://blue_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Health Check (필요할 경우 블루 환경의 헬스 체크도 추가)
        location /tig/health {
            proxy_pass http://blue_backend/tig/health;
            proxy_set_header Host $host;
        }
    }
}