name: CD

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. .env 파일 복사
      - name: Copy .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env  # GitHub Secrets에 저장된 .env 값

      # 3. Docker Compose 설치
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # 4. Docker 로그인
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 5. Docker 빌드 및 푸시
      - name: Build and push Docker image
        run: |
          docker-compose -f docker-compose.yml --env-file .env up --build -d
          docker-compose down
          docker-compose build
          docker-compose push

      # 6. 원격 서버 배포
      - name: SSH to EC2 and run deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker ps -a -q | xargs docker rm --force
            docker images -q | xargs docker rmi --force
            docker pull nimikgnoej/tig
            docker-compose -f docker-compose.yml --env-file /home/ubuntu/.env up -d