name: CD

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # Docker Compose 설치
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # 2. Docker 로그인 (DockerHub 또는 ECR 등 사용)
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3. Docker 빌드 및 푸시
      - name: Build and push Docker image
        run: |
          docker-compose -f docker-compose.yml up --build -d
          docker-compose down
          docker-compose build
          docker-compose push

      # 4. 원격 서버에 파일 전송 및 SSH 연결
      - name: SSH to EC2 and run deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}  # EC2 서버의 SSH 프라이빗 키
          script: |
            docker ps -a -q | xargs docker rm --force
            docker images -q | xargs docker rmi --force
            docker pull nimikgnoej/tig
            docker-compose -f docker-compose.yml --env-file /home/ubuntu/.env up -d